### PR TITLE
Modify jsonnet-lint to accept multiple input files

### LINKED ISSUE #543: pre-commit hook failed when committing multiple jsonnet files
[pre-commit hook of jsonnet-lint](https://github.com/google/go-jsonnet/blob/46d1fceb9c77c6494007c69a164ce3566b28e990/.pre-commit-hooks.yaml#L9-L15) failed when passing multiple jsonnet files.

```
$ pre-commit run --files a.jsonnet b.jsonnet
jsonnetfmt...............................................................Passed
jsonnet-lint.............................................................Failed
- hook id: jsonnet-lint
- exit code: 1

ERROR: only one file is allowed
```

Therefore, if you install the pre-commit hook, commits that involve changes to multiple jsonnet files will fail.
This is a little bit inconvenient for development.

Is there any reason to `jsonnet-lint` accept only one file?
May I open a pull request to change to accept multiple jsonnet files?

### PR DESCRIPTION
**Pull request by thombashi**
Close #543

### CODE REVIEW

File: linter/linter.go [hunk 1]
```diff
@@ -55,35 +65,38 @@ func lint(vm *jsonnet.VM, node nodeWithLocation, errWriter *ErrorWriter) {
...
+		for _, v := range variableInfo.Variables {
+			if len(v.Occurences) == 0 && v.VariableKind == common.VarRegular && v.Name != "$" {
+				errWriter.writeError(vm, errors.MakeStaticError("Unused variable: "+string(v.Name), v.LocRange))
+			}
 		}
-		return node
-	}, &ec)
+		ec := common.ErrCollector{}
+
+		types.Check(node.node, roots, vars, func(currentPath, importedPath string) ast.Node {
```
Comment (sbarzowski) [inline linter/linter.go:87]: This doesn't really take advantage of processing multiple files at once (it still builds the whole graph of type relationships each time). This is fine, though. We can do it as a separate change (which will be a performance-only change with no significant effect on the results).

**Comment by sbarzowski** [comment]
Thanks!
